AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  bedrock-app
  Sample SAM Template for bedrock-app

Globals:
  Function:
    Architectures:
      - x86_64
    Handler: app.lambda_handler
    Runtime: python3.11
    Layers:
      - !Ref SharedLayer
    Timeout: 3

Resources:
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Demo
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: shared-layer
      Description: Shared modules layer
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Retain
  HelloFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello-world-function
      CodeUri: functions/hello/
      Events:
        HelloApi:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref APIGateway

Outputs:
  APIGateway:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/Demo"
  HelloFn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloFn.Arn
  HelloFnRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloFnRole.Arn
