AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  bedrock-app
  Sample SAM Template for bedrock-app

Globals:
  Function:
    Architectures:
      - x86_64
    Timeout: 3

Resources:
  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Demo
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: openapi/schema.yaml
  HelloFn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Hello World Function
      CodeUri: functions/hello/
      Handler: app.lambda_handler
      Runtime: python3.13

Outputs:
  APIGateway:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${APIGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/aws-sam-bedrock-app/"
  HelloFn:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloFn.Arn
  HelloFnRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloFnRole.Arn
