# generated by datamodel-codegen:
#   filename:  schema.yaml
#   timestamp: 2024-12-31T07:35:29+00:00

from __future__ import annotations

from pydantic import BaseModel


class Hello(BaseModel):
    message: str
